name: StarCrew
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - agat=1.5.1
  - blast=2.17.0
  - bioconductor-ggtree=3.14.0
  - bioconductor-syntenet=1.8.0
  - biopython=1.86
  - clipkit=2.7.0
  - diamond=2.1.17
  - foldseek=10.941cd33
  - gffutils=0.13
  - gotree=0.5.1
  - hhsuite=3.3.0
  - hmmer=3.4
  - iqtree=3.0.1
  - macse=2.07
  - metaeuk=7.bba0d80
  - networkx=3.6.1
  - numpy=2.3.5
  - orthofinder=3.1.0
  - pandas=2.3.3
  - python=3.11.14
  - r-ape=5.8_1
  - r-base=4.4.3
  - r-bc3net=1.0.5
  - r-dendextend=1.19.1
  - r-dplyr=1.1.4
  - r-essentials=4.4
  - r-future=1.68.0
  - r-gggenomes=1.1.2
  - r-ggnewscale=0.5.2
  - r-ggplot2=3.5.2
  - r-mrfdepth=1.0.17
  - r-nbclust=3.0.1
  - r-optparse=1.7.5
  - r-reshape2=1.4.5
  - r-scales=1.4.0
  - r-systemfonts=1.3.1
  - r-svglite=2.2.2
  - r-viridis=0.6.5
  - scikit-learn=1.8.0
  - seqkit=2.12.0
